// reacthero/src/dashboard/components/dashboard.component.tsx
<h3>Top Heroes</h3>
<div class="grid grid-pad">
  <div *ngFor="let hero of heroes" [routerLink]="['/detail', hero.id]"  class="col-1-4">
    <div class="module hero">
      <h4>{{hero.name}}</h4>
    </div>
  </div>
</div>
<app-hero-search></app-hero-search>

import * as React from 'react';
import { Link } from 'react-router-dom';
import { HEROES } from '../mock-heroes';

// const logo = require('./logo.svg');

class Heroes extends React.Component {
  render() {
    return (
      <div>
        <h2>My Heroes</h2>
        <ul className="heroes">
          {HEROES.map((hero, i) =>
            (
              <li>
                <Link to={`/detail/${hero.id}`}>{hero.id}</Link>
                <a href="/detail/{hero.id}">
                  <span className="badge">{hero.id}</span>{hero.name}
                </a>
              </li>
            ))}
        </ul>
      </div>
    );
  }
}

// src/app/dashboard.component.ts
import { Component , OnInit } from '@angular/core';
import { Hero } from './hero';
import { HeroService } from './hero.service';

@Component({
  selector: 'my-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: [ './dashboard.component.css' ]
  // template: `
  // <h3>Top Heroes</h3>
  // <div class="grid grid-pad">
  //   <div *ngFor="let hero of heroes" [routerLink]="['/detail', hero.id]"  class="col-1-4">
  //     <div class="module hero">
  //       <h4>{{hero.name}}</h4>
  //     </div>
  //   </div>
  // </div>
  // `
})
export class DashboardComponent implements OnInit {

  heroes: Hero[] = [];

  constructor(private heroService: HeroService) { }

  ngOnInit(): void {
    this.heroService.getHeroes()
      .then(heroes => this.heroes = heroes.slice(1, 5));
  }
}

<h3>Top Heroes</h3>
<div class="grid grid-pad">
  <div *ngFor="let hero of heroes" [routerLink]="['/detail', hero.id]"  class="col-1-4">
    <div class="module hero">
      <h4>{{hero.name}}</h4>
    </div>
  </div>
</div>
