// reacthero/src/heroes.component.tsx
import * as React from 'react';
import { Link } from 'react-router-dom';
import { HEROES } from 'data-access/mock-heroes';

// const logo = require('./logo.svg');

class Heroes extends React.Component {
  render() {
    return (
      <div>
        <h2>My Heroes</h2>
        <ul className="heroes">
          {HEROES.map((hero, i) =>
            (
              <li>
                <Link to={`/detail/${hero.id}`}>{hero.id}</Link>
                <a href="/detail/{hero.id}">
                  <span className="badge">{hero.id}</span>{hero.name}
                </a>
              </li>
            ))}
        </ul>
      </div>
    );
  }
}

/* <h1>{{title}}</h1>
<h2>My Heroes</h2>
<ul class="heroes">
  <li *ngFor="let hero of heroes">
    <a routerLink="/detail/{{hero.id}}">
      <span class="badge">{{hero.id}}</span> {{hero.name}}
    </a>
    <button class="delete" title="delete hero"
    (click)="delete(hero)">x</button>
  </li>
</ul>
<div *ngIf="selectedHero">
  <h2>
    {{selectedHero.name | uppercase}} is my hero
  </h2>
  <button (click)="gotoDetail()">View Details</button>
</div>
<!-- <hero-detail [hero]="selectedHero"></hero-detail> --> */

export default Heroes;

// src/app/heroes.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { Hero } from './hero';
import { HeroService } from './hero.service';

@Component({
  selector: 'my-heroes',
  styleUrls: ['./heroes.component.css'],
  templateUrl: './heroes.component.html',
  // template: `
  //   <h1>{{title}}</h1>
  //   <h2>My Heroes</h2>
  //   <ul class="heroes">
  //     <li *ngFor="let hero of heroes"
  //     [class.selected]="hero === selectedHero"
  //     (click)="onSelect(hero)">
  //       <span class="badge">{{hero.id}}</span> {{hero.name}}
  //     </li>
  //   </ul>
  //   <hero-detail [hero]="selectedHero"></hero-detail>
  //   `,
  //providers: [HeroService]
})
export class HeroesComponent implements OnInit {
  constructor(
    private router: Router, private heroService: HeroService) { }
  selectedHero: Hero;
  heroes: Hero[];
  ngOnInit(): void {
    this.getHeroes();
  }
  onSelect(hero: Hero): void {
    this.selectedHero = hero;
  }
  getHeroes(): void {
    this.heroService.getHeroes().then(
      heroes => this.heroes = heroes);
  }
  gotoDetail(): void {
    this.router.navigate(['/detail', this.selectedHero.id]);
  }
}

<h1>{{title}}</h1>
<h2>My Heroes</h2>
<div>
  <label>Hero name:</label>
  <input #heroName />
  <button (click)="add(heroName.value); heroName.value=''">
    Add
  </button>
</div>
<ul class="heroes">
  <li *ngFor="let hero of heroes" [class.selected]="hero === selectedHero" (click)="onSelect(hero)">
    <span class="badge">{{hero.id}}</span>
    <span>{{hero.name}}</span>
    <button class="delete" (click)="delete(hero); $event.stopPropagation()">x</button>
  </li>
</ul>
<div *ngIf="selectedHero">
  <h2>
    {{selectedHero.name | uppercase}} is my hero
  </h2>
  <button (click)="gotoDetail()">View Details</button>
</div>
<!-- <hero-detail [hero]="selectedHero"></hero-detail> -->
